### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by simon-curtis**
- Basic readme written, with example implementation.

- Added: 
  - `INTERFACE` ITotpSetup
  - `CLASS` TotpSetup
  - `INTERFACE` IQrCodeImage
  - `CLASS` QrCodeImage

- TotpSetup
  - Moved to main project as this is an implementation, not an interface.
  - Extracted interface into `AspNetCore.Totp.Interface`
  - Converted `public string QrCodeImage` to `private readonly IQrCodeImage _qrCodeImage`
  - Added `QrCodeImageBytes` method for easy access to the QrCodeImage bytes
  - Added test to make sure there are no side effects when setting the image bytes.

- TotpSetupGenerator
  - Made `GetQrImage` now return byte[] instead of string to use in the QrCodeImage constructor

- Test have been run and all pass

### CODE REVIEW

**Review by verloka — APPROVED** [review]

**Review by verloka — APPROVED** [review]

**Review by verloka — APPROVED** [review]

**Review by verloka — APPROVED** [review]

**Comment by simon-curtis** [comment]
@damirkusar would you like me to join the contributors to help with maintenance of this project?

**Comment by damirkusar** [comment]
@simon-curtis, that would be awesome, because I currently have not really much time. Thanks for your offer.

**Comment by damirkusar** [comment]
@simon-curtis, you have also a nuget package user? will add you there as well if you like..

**Comment by simon-curtis** [comment]
@damirkusar I will create a CI/CD pipeline to automatically push it to nuget, I have already created the project for it - I am working on it on my fork and will submit a pull request

**Pull request merged**
